smartagro/core/urls.py
from django.conf.urls import include, url

from . import views

#app_name = 'core'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    
    # data
    url(r'^data$', views.data, name='data'),
    
    # machines
    url(r'^machines$', views.MachineList.as_view(), name='machine_list'),
    url(r'^machine/add$', views.MachineCreate.as_view(), name='machine_add'),
    url(r'^machine/detail/(?P<machine_id>.+)$', views.MachineDetail.as_view(), name='machine_detail'),
    url(r'^machine/edit/(?P<machine_id>.+)$', views.MachineUpdate.as_view(), name='machine_edit'),
    url(r'^machine/delete/(?P<machine_id>.+)$', views.MachineDelete.as_view(), name='machine_delete'),
    
    # persons
    url(r'^persons$', views.PersonList.as_view(), name='person_list'),
    url(r'^person/add$', views.PersonCreate.as_view(), name='person_add'),
    url(r'^person/detail/(?P<person_id>.+)$', views.PersonDetail.as_view(), name='person_detail'),
    url(r'^person/edit/(?P<person_id>.+)$', views.PersonUpdate.as_view(), name='person_edit'),
    url(r'^person/delete/(?P<person_id>.+)$', views.PersonDelete.as_view(), name='person_delete'),
    
    # fields
    url(r'^fields$', views.FieldList.as_view(), name='field_list'),
    url(r'^field/add$', views.FieldCreate.as_view(), name='field_add'),
    url(r'^field/detail/(?P<field_id>.+)/$', views.FieldDetail.as_view(), name='field_detail'),
    url(r'^field/edit/(?P<field_id>.+)$', views.FieldUpdate.as_view(), name='field_edit'),
    url(r'^field/delete/(?P<field_id>.+)$', views.FieldDelete.as_view(), name='field_delete'),
    
    # fertilizers
    url(r'^fertilizers$', views.FertilizerList.as_view(), name='fertilizer_list'),
    url(r'^fertilizer_activate$', views.fertilizer_activate, name='fertilizer_activate'),
    url(r'^fertilizer/detail/(?P<fertilizer_id>.+)/$', views.FertilizerDetail.as_view(), name='fertilizer_detail'),
    
    # plant protectants
    url(r'^plantprotectants$', views.PlantProtectantList.as_view(), name='plant_protectant_list'),
    url(r'^plantprotectant_activate$', views.plantprotectant_activate, name='plant_protectant_activate'),
    url(r'^plantprotectant/detail/(?P<plant_protectant_id>.+)/$', views.PlantProtectantDetail.as_view(), name='plant_protectant_detail'),
    
    # 
    url(r'^seeds$', views.SeedList.as_view(), name='seed_list'),
    url(r'^seed_activate$', views.seed_activate, name='seed_activate'),
    url(r'^seed/detail/(?P<seed_id>.+)/$', views.SeedDetail.as_view(), name='seed_detail'),
    
    # documentations
    url(r'^documentations$', views.DocumentationList.as_view(), name='documentation_list'),
    url(r'^documentation/add$', views.DocumentationCreate.as_view(), name='documentation_add'),
    url(r'^documentation/detail/(?P<documentation_id>.+)/$', views.DocumentationDetail.as_view(), name='documentation_detail'),
    url(r'^documentation/edit/(?P<documentation_id>.+)$', views.DocumentationUpdate.as_view(), name='documentation_edit'),
    url(r'^documentation/delete/(?P<documentation_id>.+)$', views.DocumentationDelete.as_view(), name='documentation_delete'),
    
    url(r'^accounts/', include('accounts.urls')),     
]

smartagro/smartagro/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('core.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartagro/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from operator import attrgetter
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe

"""
 	Links
	* https://wsvincent.com/django-referencing-the-user-model/
"""

"""
--------------------------------------------------------------
	user related data
--------------------------------------------------------------
"""

class Manufacturer(models.Model):
	name = models.CharField(max_length=64)
	description = models.CharField(max_length=512, null=True, blank=True)
	
	def __unicode__(self):
		return '%s' % (self.name)

MACHINE_TYPES = (('T', _('Tractor')), ('I', _('Implement')), ('H', _('Harvester')))

class Model(models.Model):
	name = models.CharField(max_length=64)
	manufacturer = models.ForeignKey(Manufacturer)
	
	# used as preset
	type = models.CharField(max_length=1, choices=MACHINE_TYPES)
	horsepower = models.IntegerField(null=True, blank=True)
	volume = models.IntegerField(null=True, blank=True)
	width = models.IntegerField(null=True, blank=True)
	
	def __unicode__(self):
		return '%s' % (self.name)

FERTILIZER_TYPES = (('O', _('Organic')), ('M', _('Mineralic')))

class Fertilizer(models.Model):
	name = models.CharField(max_length=64)
	type = models.CharField(max_length=1, choices=FERTILIZER_TYPES)
	
	def __unicode__(self):
		return '%s' % (self.name)

class CultureType(models.Model):
	name = models.CharField(max_length=64)
	abbreviation = models.CharField(max_length=2)
	
	def __unicode__(self):
		return '%s' % (self.name)
		
class Culture(models.Model):
	name = models.CharField(max_length=64)
	type = models.ForeignKey(CultureType)
	
	def __unicode__(self):
		return '%s - %s' % (self.name, self.type.name)

class Seed(models.Model):
	name = models.CharField(max_length=64)
	culture = models.ForeignKey(Culture)
	
	def __unicode__(self):
		return '%s - %s' % (self.name, self.culture.name)

class PlantProtectantCategory(models.Model):
	name = models.CharField(max_length=64)
	
	def __unicode__(self):
		return '%s' % (self.name)
	
class PlantProtectant(models.Model):
	name = models.CharField(max_length=64)
	category = models.ForeignKey(PlantProtectantCategory)
	valid_cultures = models.ManyToManyField(Culture)
	
	def __unicode__(self):
		return '%s - %s' % (self.name, self.category.name)

"""
--------------------------------------------------------------
	user related data
--------------------------------------------------------------
"""

class Machine(models.Model):
	"""
		Class that holds the machines
	"""
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=64)
	model = models.ForeignKey(Model, on_delete=models.CASCADE, null=True, blank=True)
	image = models.ImageField(upload_to='media/machines', blank=True, null=True)
	
	# preset from model (can be changed)
	type = models.CharField(max_length=1, choices=MACHINE_TYPES)
	horsepower = models.IntegerField(null=True, blank=True)
	volume = models.IntegerField(null=True, blank=True)
	width = models.IntegerField(null=True, blank=True)
	
	def thumbnail(self):
		"""
			Returns an extendable version of the 'image' of this machine as html or a default image
		"""
		if self.image.name is not None and self.image.name <> '':
			return mark_safe('<a href="/media/%s"><img border="0" alt="" src="/media/%s" height="40" /></a>' % ((self.image.name, self.image.name)))
		else:
			return mark_safe('<img border="0" alt="" src="/static/core/images/machine.png" height="40" />')
	thumbnail.allow_tags = True
	
	def get_absolute_url(self):
		"""
			Returns the url to access a particular machine instance.
		"""
		return reverse('machine_detail', args=[str(self.id)])
	
	def __unicode__(self):
		return '%s' % (self.name)
	
class Person(models.Model):
	"""
		Class that holds the persons
	"""
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=64)
	last_name = models.CharField(max_length=64)
	image = models.ImageField(upload_to='media/persons', blank=True, null=True)
	
	def thumbnail(self):
		"""
			Returns an extendable version of the 'image' of this person as html or a default image
		"""
		if self.image.name is not None and self.image.name <> '':
			return mark_safe('<a href="/media/%s"><img border="0" alt="" src="/media/%s" height="40" /></a>' % ((self.image.name, self.image.name)))
		else:
			return mark_safe('<img border="0" alt="" src="/static/core/images/person.png" height="40" />')
	thumbnail.allow_tags = True
	
	def get_absolute_url(self):
		"""
			Returns the url to access a particular person instance.
		"""
		return reverse('person_detail', args=[str(self.id)])
	
	def __unicode__(self):
		return '%s %s' % (self.first_name, self.last_name)


class Field(models.Model):
	"""
		Class that holds the fields
	"""
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=64)
	area = models.IntegerField()
	
	def documentations(self):
		"""
			Returns the documentations that happend on that field
			- ordered by date
		"""
		documentationArray = []
		
		for fieldRelation in DocumentationFieldRelation.objects.filter(field = self):
			documentationArray.append(fieldRelation.documentation)
		
		documentationArray = sorted(documentationArray, key=attrgetter('date'), reverse=False)
		
		return documentationArray
	
	def get_absolute_url(self):
		"""
			Returns the url to access a particular field instance.
		"""
		return reverse('field_detail', args=[str(self.id)])
	
	def __unicode__(self):
		return '%s - %d ha' % (self.name, self.area)


class FertilizerRelation(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	fertilizer = models.ForeignKey(Fertilizer)
	active = models.NullBooleanField(default=False)
	
	def __unicode__(self):
		return '%s - %s' % (self.fertilizer.name, self.active)
		
class SeedRelation(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	seed = models.ForeignKey(Seed)
	active = models.NullBooleanField(default=False)
	
	def __unicode__(self):
		return '%s - %s' % (self.seed.name, self.active)
		
class PlantProtectantRelation(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	plant_protectant = models.ForeignKey(PlantProtectant)
	active = models.NullBooleanField(default=False)
	
	def __unicode__(self):
		return '%s - %s' % (self.plant_protectant.name, self.active)
	
DOCUMENTATION_TYPES = (('W', _('Plowing')), ('S', _('Sowing')), ('H', _('Harvesting')), ('F', _('Fertilization')), ('C', _('Cropcare')), ('P', _('Plantprotect')), )
DOCUMENTATION_STATUS = (('P', _('Planned')), ('S', _('Saved')), ('B', _('Booked')))

class Documentation(models.Model):
	"""
		Class that holds all documentation related connections
	"""
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateField()
	duration = models.IntegerField() # in minutes
	type = models.CharField(max_length=1, choices=DOCUMENTATION_TYPES)
	status = models.CharField(max_length=1, choices=DOCUMENTATION_STATUS)
	comments = models.CharField(max_length=64)
	
	def get_absolute_url(self):
		"""
			Returns the url to access a particular documentation instance.
		"""
		return reverse('documentation_detail', args=[str(self.id)])
	
	def fields(self):
		"""
			Returns the fields that are linked to this documentation
		"""
		fieldArray = []
	
		for fieldRelation in DocumentationFieldRelation.objects.filter(documentation = self):
			fieldArray.append(fieldRelation.field)
		
		return fieldArray
		
	def machines(self):
		"""
			Returns the machines that are linked to this documentation
		"""
		machineArray = []
		
		for machineRelation in DocumentationMachineRelation.objects.filter(documentation = self):
			machineArray.append(machineRelation.machine)
		
		return machineArray
		
	def persons(self):
		"""
			Returns the persons that are linked to this documentation
		"""
		personArray = []
		
		for personRelation in DocumentationPersonRelation.objects.filter(documentation = self):
			personArray.append(personRelation.person)
		
		return personArray
		
	def fertilizers(self):
		"""
			Returns the fertilizers that are linked to this documentation
		"""
		fertilizerArray = []
		
		for fertilizerRelation in DocumentationFertilizerRelation.objects.filter(documentation = self):
			fertilizerArray.append(fertilizerRelation.fertilizer)
		
		return fertilizerArray
		
	def plant_protectants(self):
		"""
			Returns the plant protectants that are linked to this documentation
		"""
		plantProtectantsArray = []
		
		for plantProtectantRelation in DocumentationPlantProtectantRelation.objects.filter(documentation = self):
			plantProtectantsArray.append(plantProtectantRelation.plant_protectant)
		
		return plantProtectantsArray
		
	def seeds(self):
		"""
			Returns the seeds that are linked to this documentation
		"""
		seedArray = []
		
		for seedRelation in DocumentationSeedRelation.objects.filter(documentation = self):
			seedArray.append(seedRelation.seed)
		
		return seedArray
	
	def __unicode__(self):
		return '%s - %s' % (self.date, self.type)
		
class DocumentationFieldRelation(models.Model):
	"""
		class that holds the relation between documentations and fields
	"""
	documentation = models.ForeignKey(Documentation, on_delete=models.CASCADE)
	field = models.ForeignKey(Field, on_delete=models.CASCADE, blank=True, null=True)
	
	def __unicode__(self):
		return '%s - %s' % (self.documentation, self.field)
	
class DocumentationMachineRelation(models.Model):
	"""
		class that holds the relation between documentations and machines
	"""
	documentation = models.ForeignKey(Documentation, on_delete=models.CASCADE)
	machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
	
	def __unicode__(self):
		return '%s - %s' % (self.documentation, self.machine)
	
class DocumentationPersonRelation(models.Model):
	"""

smartagro/core/forms.py
from django.db import models
from django.forms import inlineformset_factory
from django.forms import ModelForm
from django.contrib import admin
from django import forms
import re # regular expression library

from core.models import Machine, Person, Field, Documentation, DocumentationFieldRelation, DocumentationMachineRelation, DocumentationPersonRelation, DocumentationFertilizerRelation, DocumentationPlantProtectantRelation, DocumentationSeedRelation

# https://www.caktusgroup.com/blog/2018/05/07/creating-dynamic-forms-django/

class FertilizerActivationForm(forms.Form):
	fertilizer_id = forms.CharField(max_length=10, required=True)
	activated = forms.CharField(max_length=255, required=True)

class PlantProtectantActivationForm(forms.Form):
	plant_protectant_id = forms.CharField(max_length=10, required=True)
	activated = forms.CharField(max_length=255, required=True)

class SeedActivationForm(forms.Form):
	seed_id = forms.CharField(max_length=10, required=True)
	activated = forms.CharField(max_length=255, required=True)

class DocumentationFieldRelationForm(ModelForm):
	class Meta:
		model = DocumentationFieldRelation
		exclude = ()
		
class DocumentationMachineRelationForm(ModelForm):
	class Meta:
		model = DocumentationMachineRelation
		exclude = ()
		
class DocumentationPersonRelationForm(ModelForm):
	class Meta:
		model = DocumentationPersonRelation
		exclude = ()
		
class DocumentationFertilizerRelationForm(ModelForm):
	class Meta:
		model = DocumentationFertilizerRelation
		exclude = ()
		
class DocumentationPlantProtectantRelationForm(ModelForm):
	class Meta:
		model = DocumentationPlantProtectantRelation
		exclude = ()
		
class DocumentationSeedRelationForm(ModelForm):
	class Meta:
		model = DocumentationSeedRelation
		exclude = ()

DocumentationFieldRelationFormset = inlineformset_factory(Documentation, DocumentationFieldRelation, form=DocumentationFieldRelationForm, extra=1)
DocumentationMachineRelationFormset = inlineformset_factory(Documentation, DocumentationMachineRelation, form=DocumentationMachineRelationForm, extra=1)
DocumentationPersonRelationFormset = inlineformset_factory(Documentation, DocumentationPersonRelation, form=DocumentationPersonRelationForm, extra=1)
DocumentationFertilizerRelationFormset = inlineformset_factory(Documentation, DocumentationFertilizerRelation, form=DocumentationFertilizerRelationForm, extra=1)
DocumentationPlantProtectantRelationFormset = inlineformset_factory(Documentation, DocumentationPlantProtectantRelation, form=DocumentationPlantProtectantRelationForm, extra=1)
DocumentationSeedRelationFormset = inlineformset_factory(Documentation, DocumentationSeedRelation, form=DocumentationSeedRelationForm, extra=1)

smartagro/smartagro/templates/core/data/field_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="{% url 'index' %}"><i class="fa fa-home w3-margin-right"></i></a></li>
   		<li><a href="{% url 'field_list' %}">Fields</a></li>
    	<li class="last active"><a href="{% url 'field_detail' object.pk %}">{{ object }}</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Documentations</h4>
		<h6>Why should I add my documentations?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<br />
				<img src="{% static 'core/images/field.png' %}" alt="Field" class="w3-left w3-margin-right" style="width:60px">
				<h4>Fields</h4>
				<hr class="w3-clear">
				<form action="" method="post">
					{% csrf_token %}
            		<p>Are you sure you want to delete "{{ object }}"?</p>
            		<input type="submit" class="w3-button w3-theme-d1" value="Confirm"/> <a href="{% url 'field_detail' object.pk %}" class="w3-button w3-theme-d1">Abbrechen</a>
        		</form> 
			</div>
  		</div>
	</div>
</div>

{% endblock %}

smartagro/smartagro/templates/core/data/field_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="{% url 'index' %}"><i class="fa fa-home w3-margin-right"></i></a></li>
    	<li><a href="{% url 'field_list' %}">Fields</a></li>
    	<li class="last active"><a href="{% url 'field_detail' object.pk %}">{{ object }}</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Machines</h4>
		<h6>Why should I add my machines?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<br/>
				<img src="{% static 'core/images/field.png' %}" alt="Field" class="w3-left w3-margin-right" style="width:40px">
				<h4>Field</h4>
				<hr class="w3-clear">
				<table class="w3-table w3-striped">
					<tr>
						<td>Name</td>
						<td>{{ object.name }}</td>
					</tr>
					<tr>
						<td>Area</td>
						<td>{{ object.area }} ha</td>
					</tr>
				</table>
				<p>
					<a href="{% url 'field_edit' object.pk %}" class="w3-button w3-theme-d1">Edit</a>
					<a href="{% url 'field_delete' object.pk %}" class="w3-button w3-theme-l4">Delete</a>
				</p>
			</div>
        </div>
	</div>
</div>
<br />
<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<img src="{% static 'core/images/documentation.png' %}" alt="Avatar" class="w3-left w3-margin-right" style="width:40px">
				<h4>Recent documentations</h4>
				<hr class="w3-clear">
				<ul>
					{% for documentation in object.documentations %}
						<li>{{ documentation.date }} {{ documentation.get_type_display }}</li>
					{% endfor %}
				</ul>
				<a href="{% url 'documentation_add' %}" class="w3-button w3-theme-d1">New documentation</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

smartagro/smartagro/templates/core/data/field_form.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="{% url 'index' %}"><i class="fa fa-home w3-margin-right"></i></a></li>
   		<li class="last active"><a href="{% url 'field_list' %}">Fields</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Documentations</h4>
		<h6>Why should I add my documentations?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<br/>
				<img src="{% static 'core/images/documentation.png' %}" alt="Documentation" class="w3-left w3-margin-right" style="width:60px">
				{% if object %}
					<h4>Edit {{ object }}</h4>
				{% else %}
					<h4>New field</h4>
				{% endif %}
				<hr class="w3-clear">
				<p>
					<form action="" method="post">
						{% csrf_token %}
        				{{ form.as_p }}
						<input type="submit" class="w3-button w3-theme-d1" value="Save"/> <a href="{% url 'field_list' %}" class="w3-button w3-theme-d1">back to the list</a>
					</form>
				</p>
			</div>
  		</div>
	</div>
</div>
<br />

{% endblock %}

smartagro/smartagro/templates/core/data/field_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="{% url 'index' %}"><i class="fa fa-home w3-margin-right"></i></a></li>
    	<li><a href="{% url 'data' %}">Data</a></li>
    	<li class="last active"><a href="{% url 'field_list' %}">Fields</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Fields</h4>
		<h6>Why should I add my fields?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<br />
				<img src="{% static 'core/images/field.png' %}" alt="Avatar" class="w3-left w3-margin-right" style="width:60px">
	  			<h4>List of fields</h4>
	  			<hr class="w3-clear">
	  			<table class="w3-table w3-striped">
	  				<tr>
	  					<th>#</th>
	  					<th>name</th>
	  					<th>area</th>
	  					<th>Action</th>
	  				</tr>
	  				{% for field in object_list %}
	  				<tr>
	  					<td>{{ forloop.counter }}</td>
	  					<td>{{ field.name }}</td>
	  					<td>{{ field.area }}</td>
	  					<td><a href="{% url 'field_detail' field.pk %}" class="w3-button w3-theme-d1">Detail</a></td>
	  				</tr>
	  				{% endfor %}
	  			</table>
	  			<br />
	  			<a href="{% url 'field_add' %}" class="w3-button w3-theme-d1">add a field</a>
			</div>
  		</div>
	</div>
</div>

{% endblock %}

smartagro/smartagro/templates/core/data/machine_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="{% url 'index' %}"><i class="fa fa-home w3-margin-right"></i></a></li>
   		<li><a href="{% url 'data' %}">Data</a></li>
   		<li><a href="{% url 'machine_list' %}">Machines</a></li>
    	<li class="last active"><a href="{% url 'machine_detail' object.pk %}">{{ object }}</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Machines</h4>
		<h6>Why should I add my machines?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-row-padding">
	<div class="w3-col m12">
  		<div class="w3-card w3-round w3-white">
			<div class="w3-container w3-padding">
				<br />
				<img src="{% static 'core/images/machine.png' %}" alt="Machine" class="w3-left w3-margin-right" style="width:60px">
				<h4>Machines</h4>
				<hr class="w3-clear">
				<form action="" method="post">
					{% csrf_token %}
            		<p>Are you sure you want to delete "{{ object }}"?</p>
            		<input type="submit" class="w3-button w3-theme-d1" value="Confirm"/> <a href="{% url 'machine_detail' object.pk %}" class="w3-button w3-theme-l4">Abbrechen</a>
        		</form> 
			</div>
  		</div>
	</div>
</div>

{% endblock %}

smartagro/smartagro/templates/core/data/machine_edit.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block breadcrumbs %}
 	<ul class="breadcrumbs">
   		<li class="first"><a href="/core/index"><i class="fa fa-home w3-margin-right"></i></a></li>
   		<li><a href="/core/data">Data</a></li>
    	<li><a href="/core/machines">Machines</a></li>
    	<li class="last active"><a href="/core/machine/detail/{{ machine.id }}">{{ machine }}</a></li>
  	</ul>
{% endblock %}

{% block profile %}

<div class="w3-card w3-round w3-white">
	<div class="w3-container">
		<h4 class="w3-center">Machines</h4>
		<h6>Why should I add my machines?</h6>
		Because it's fun.
		<br />
		<br />
	</div>
</div>
<br />

{% endblock %}

{% block content %}

<div class="w3-container w3-card w3-white w3-round w3-margin">
	<br/>
	<img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
	<h4>Edit machine</h4><br />
	<hr class="w3-clear">
	<p>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			
			{% for field in form %}
      			<p>
					{{ field.label_tag }}<br>
					{{ field }}
					{% if field.help_text %}
						<small style="color: grey">{{ field.help_text }}</small>
					{% endif %}
					{% for error in field.errors %}
						<p style="color: red">{{ error }}</p>
					{% endfor %}
      			</p>
    		{% endfor %}
			
			<button type="submit">Save machine</button>
		</form>
	</p>
</div>

{% endblock %}